src/Entity/Project.php
<?php

namespace App\Entity;

use App\Repository\ProjectRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Symfony\Component\Validator\Constraints\GreaterThan;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: ProjectRepository::class)]
class Project
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $name = null;

    #[ORM\OneToMany(mappedBy: 'project', targetEntity: StudentGroup::class)]
    private Collection $studentGroups;

    #[ORM\Column]
    #[GreaterThan(0)]
    private ?int $max_students_per_group = null;

    #[GreaterThan(0)]
    private ?int $num_groups = null;

    #[ORM\OneToMany(mappedBy: 'project', targetEntity: Student::class, orphanRemoval: true)]
    private Collection $students;

    public function __construct()
    {
        $this->studentGroups = new ArrayCollection();
        $this->students = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    /**
     * @return Collection<int, StudentGroup>
     */
    public function getStudentGroups(): Collection
    {
        return $this->studentGroups;
    }

    public function addStudentGroup(StudentGroup $studentGroup): self
    {
        if (!$this->studentGroups->contains($studentGroup)) {
            $this->studentGroups->add($studentGroup);
            $studentGroup->setProject($this);
        }

        return $this;
    }

    public function removeStudentGroup(StudentGroup $studentGroup): self
    {
        if ($this->studentGroups->removeElement($studentGroup)) {
            // set the owning side to null (unless already changed)
            if ($studentGroup->getProject() === $this) {
                $studentGroup->setProject(null);
            }
        }

        return $this;
    }

    public function getMaxStudentsPerGroup(): ?int
    {
        return $this->max_students_per_group;
    }

    public function setMaxStudentsPerGroup(int $max_students_per_group): self
    {
        $this->max_students_per_group = $max_students_per_group;

        return $this;
    }

    /**
     * Get the value of num_groups
     */ 
    public function getNumGroups()
    {
        return $this->num_groups;
    }

    /**
     * Set the value of num_groups
     *
     * @return  self
     */ 
    public function setNumGroups($num_groups)
    {
        $this->num_groups = $num_groups;

        return $this;
    }

    /**
     * @return Collection<int, Student>
     */
    public function getStudents(): Collection
    {
        return $this->students;
    }

    public function addStudent(Student $student): self
    {
        if (!$this->students->contains($student)) {
            $this->students->add($student);
            $student->setProject($this);
        }

        return $this;
    }

    public function removeStudent(Student $student): self
    {
        if ($this->students->removeElement($student)) {
            // set the owning side to null (unless already changed)
            if ($student->getProject() === $this) {
                $student->setProject(null);
            }
        }

        return $this;
    }

    public function getGroupPositions(): ?array
    {
        if(!empty($this->studentGroups))
        {
            $groupPositions = [];
            $pos = 1;
            foreach($this->studentGroups->toArray() as $group)
            {
                $groupPositions[$group->getId()] = $pos++;
            }
            return $groupPositions;
        }
        return null;
    }

    public function __toString()
    {
        return $this->id;
    }
}

src/Form/ProjectType.php
<?php

namespace App\Form;

use App\Entity\Project;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\NumberType;

class ProjectType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('name')
            ->add('num_groups')
            ->add('max_students_per_group')
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Project::class,
        ]);
    }
}

src/Controller/ProjectController.php
<?php

namespace App\Controller;

use App\Entity\Project;
use App\Form\ProjectType;
use App\Repository\ProjectRepository;
use App\Repository\StudentRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use App\Service\InitProjectGroupsService;


class ProjectController extends AbstractController
{
    #[Route('/', name: 'app_project_index', methods: ['GET'])]
    public function index(ProjectRepository $projectRepository): Response
    {
        return $this->render('project/index.html.twig', [
            'projects' => $projectRepository->findAll(),
        ]);
    }

    #[Route('/new', name: 'app_project_new', methods: ['GET', 'POST'])]
    public function new(Request $request, ProjectRepository $projectRepository, InitProjectGroupsService $initProjectGroupsService): Response
    {
        $project = new Project();
        $form = $this->createForm(ProjectType::class, $project);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $projectRepository->save($project, true);
            $numGroups = $form->get("num_groups")->getData();
            $initProjectGroupsService->initProjectGroups($project, $numGroups);
            return $this->redirectToRoute('app_project_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('project/new.html.twig', [
            'project' => $project,
            'form' => $form,
        ]);
    }

    #[Route('/{id}/status', name: 'app_project_status', methods: ['GET', 'POST'])]
    public function status(Request $request, StudentRepository $studentRepository, Project $project): Response
    {
        $studentsWithoutGroup = $studentRepository->findByProject($project);
        return $this->render('project/status.html.twig', [
            'project' => $project,
            'groupPositions' => $project->getGroupPositions(),
            'projectGroups' => $project->getStudentGroups(),
            'studentsWithoutGroup' => $studentsWithoutGroup
        ]);
    }

    #[Route('/{id}', name: 'app_project_delete', methods: ['POST'])]
    public function delete(Request $request, Project $project, ProjectRepository $projectRepository): Response
    {
        if ($this->isCsrfTokenValid('delete'.$project->getId(), $request->request->get('_token'))) {
            $projectRepository->remove($project, true);
        }

        return $this->redirectToRoute('app_project_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/project/_form.html.twig
{{ form_start(form) }}
    <div class="form-group">
        {{ form_row(form.name, {'attr': {'class' : 'form-control'}}) }}
    </div>
    <div class="form-group">
        {{ form_row(form.num_groups, {'attr': {'class' : 'form-control'}}) }}
    </div>
    <div class="form-group">
        {{ form_row(form.max_students_per_group, {'attr': {'class' : 'form-control'}}) }}
    </div>
    <button class="btn btn-primary mt-3">{{ button_label|default('Save') }}</button>

{{ form_end(form) }}

templates/project/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Project index{% endblock %}

{% block body %}

    <div class="w-50 container-fluid">
        <h3 class='text-center'>Project index</h3>
        <table class="table">
            <thead>
                <tr>
                    <th>Id</th>
                    <th>Name</th>
                    <th>Groups</th>
                    <th>Max students per group</th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
            {% for project in projects %}
                <tr>
                    <td>{{ project.id }}</td>
                    <td>{{ project.name }}</td>
                    <td>{{ project.studentGroups|length }}</td>
                    <td>{{ project.maxStudentsPerGroup }}</td>
                    <td>
                        <a href="{{ path('app_project_status', {'id': project.id}) }}">Status</a>
                    </td>
                </tr>
            {% else %}
                <tr>
                    <td colspan="4">no records found</td>
                </tr>
            {% endfor %}
            </tbody>
        </table>

        <a class="btn btn-primary" href="{{ path('app_project_new') }}">Create new</a>
    </div>
{% endblock %}

templates/project/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Project{% endblock %}

{% block body %}

<div class="w-50 container-fluid">
    <h3 class='text-center'>Create new Project</h3>
    {{ include('project/_form.html.twig') }}
    <a class='btn btn-dark mt-3' href="{{ path('app_project_index') }}">back to list</a>
</div>
{% endblock %}

templates/project/status.html.twig
{% extends 'base.html.twig' %}

{% block title %}Project status page{% endblock %}

{% block body %}
    {% for error in app.flashes('error') %}
        {{ error }}
    {% endfor %}
    <div id="project-content">
        <div class="w-50 container-fluid students-container">
            <div class="text-center">
                <h3>Project status page</h3>
                <div class="d-grid gap-1">
                    <div class="ms-3 p-1">Project: <b>{{ project.name }}</b></div>
                    <div class="ms-3 p-1">Number of groups: <b>{{ project.studentGroups|length }}</b></div>
                    <div class="ms-3 p-1">Students per group: <b>{{ project.maxStudentsPerGroup }}</b></div>
                </div>
            </div>
            <h3>Students</h3>
            <table class="table table-dark table-hover text-center">
                <thead>
                    <tr>
                        <td>Student</td>
                        <td>Group</td>
                        <td>Actions</td>
                    <tr>
                    <tbody class="table-light">
                    {% if project.students is not empty %}
                        {% for student in project.students %}
                            <tr>
                                <td >{{student.fullname}}</td>
                                <td>
                                {% if groupPositions is not empty and student.studentGroup %}
                                    Group #{{groupPositions[student.studentGroup.id]}}
                                {% else %}
                                    -
                                {% endif %}
                                </td>
                                <td>{{ include('student/_delete_form.html.twig', {'student': student, 'project_id': project.id} ) }}</td>
                            </tr>
                        {% endfor %}
                    {% else %}
                        <tr>
                            <td class="text-center" colspan=3>No students.</td>
                        </tr>
                    {% endif %}
                    </tbody>
                </thead>
            </table>
            <a id='add-student-to-project' class="btn btn-primary my-3" href={{path('app_student_new', {'project': project.id})}}>Add new Student</a>
        </div>
        <div class="w-50 container-fluid groups-container">
            <h3>Groups</h3>
            <div class="alert alert-danger d-none" role="alert">
            </div>
            <div class="alert alert-success d-none" role="alert">
            </div>
            <div class="row">

            {% set groupsCounter = 1 %}
            {% for group in projectGroups %}
                <div class="col-6">
                {% if group.students|length == project.maxStudentsPerGroup %}
                    <div class="alert alert-dark" role="alert">
                        Group #{{ groupsCounter }} is full.
                    </div>
                {% endif %}
                <table class="table table-dark table-hover" data-group-id='{{group.id}}'>
                    <thead>
                        <tr>
                            <td class="text-center">Group #{{ groupsCounter }}</td>
                        <tr>
                    </thead>
                    <tbody class="table-light">
                        {% set studentsCounter = 1 %}
                        {% for student in group.students %}
                            <tr>
                                <td class="text-center">
                                    {{ student.fullname }} 
                                </td>
                            </tr>
                            {% set studentsCounter = studentsCounter + 1 %}
                        {% endfor %}
                        {% if studentsCounter <= project.maxStudentsPerGroup %}
                            {% for i in range(studentsCounter, project.maxStudentsPerGroup) %}
                                <tr>
                                    <td class="text-center">
                                        <select class="form-select">
                                            <option selected="true" disabled="disabled">
                                                Assign a Student
                                            </option>
                                            {% for student in studentsWithoutGroup %}
                                                <option value="{{student.id}}">{{student.fullname}}</option>
                                            {% endfor %}
                                        </select>
                                    </td>
                                </tr>
                            {% endfor %}
                        {% endif %}
                    </tbody>
                </table>
                </div>
            {% set groupsCounter = groupsCounter + 1 %}
            {% endfor %}
            </div>
            <a class='btn btn-dark mt-3' href="{{ path('app_project_index') }}">back to list</a>
        </div>
    </div>
{% endblock %}
{% block javascripts %}
    {{ parent() }}
    <script>
        const refreshInterval = 10000; // ms

        setInterval(refreshProjectStatus, refreshInterval);
    
        function refreshProjectStatus()
        {
            fetch(window.location.href, {
                method: 'GET',
            }).then(response => response.text())
            .then(function (html) {
    
                const newContentStudents = $(html).find('.students-container').html();
                const newContentGroups = $(html).find('.groups-container').html();
                $('.students-container').html(newContentStudents);
                $('.groups-container').html(newContentGroups);
            });
        }
    </script>
{% endblock %}